# Generated by Django 5.1.1 on 2024-10-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_product_pricehistory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
