# Generated by Django 5.1.1 on 2024-10-10 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_wishlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='name',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.product'),
            preserve_default=False,
        ),
    ]
