# Generated by Django 5.1.1 on 2024-10-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_wishlist_name_wishlist_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_choice',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bullet_points',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_prime_eligible',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='more_images',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_stars_distribution',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top_review',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
