# Generated by Django 5.1.1 on 2024-10-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_product_amazon_choice_product_asin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='retailer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main_app.retailer'),
        ),
    ]
