# Generated by Django 5.1.1 on 2024-10-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_pricehistory_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_width',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
        ),
    ]
