# Generated by Django 5.1.1 on 2024-10-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_product_rating_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating_width',
            field=models.IntegerField(default=75, null=True),
        ),
    ]
