# Generated by Django 5.1.1 on 2024-10-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_product_rating_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_id',
            new_name='product',
        ),
    ]
